"""initial schema

Revision ID: 0292e274ac71
Revises: 
Create Date: 2026-09-08 15:01:38.954487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0292e274ac71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_catalogue',
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('ghg_category', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('default_unit', sa.String(length=50), nullable=False),
    sa.Column('allowed_units', sa.String(length=255), nullable=False),
    sa.Column('gases', sa.String(length=100), nullable=False),
    sa.Column('factor_source', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('activity_key')
    )
    op.create_table('fuel_property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuel_key', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('density_kg_per_m3', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('ncv_mj_per_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('gas_reference', sa.String(length=50), nullable=True),
    sa.Column('basis', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_property_fuel_key'), 'fuel_property', ['fuel_key'], unique=False)
    op.create_table('gwp_set',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('organisation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('sector_code', sa.String(length=50), nullable=True),
    sa.Column('sector_scheme', sa.String(length=50), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('revenue_currency', sa.String(length=10), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emission_factor',
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('reference_year', sa.Integer(), nullable=False),
    sa.Column('gas', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('numerator_unit', sa.String(length=50), nullable=False),
    sa.Column('denominator_unit', sa.String(length=50), nullable=False),
    sa.Column('ef_basis', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_table_ref', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('factor_set_id', sa.String(length=100), nullable=False),
    sa.Column('superseded_by', sa.String(length=100), nullable=True),
    sa.Column('uncertainty_pct', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_key'], ['activity_catalogue.activity_key'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_emission_factor_activity_key'), 'emission_factor', ['activity_key'], unique=False)
    op.create_index(op.f('ix_emission_factor_gas'), 'emission_factor', ['gas'], unique=False)
    op.create_index(op.f('ix_emission_factor_reference_year'), 'emission_factor', ['reference_year'], unique=False)
    op.create_index(op.f('ix_emission_factor_region'), 'emission_factor', ['region'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('grid_region', sa.String(length=50), nullable=True),
    sa.Column('floor_area', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('production_volume', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('production_unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_organisation_id'), 'facility', ['organisation_id'], unique=False)
    op.create_table('gwp_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gwp_set_name', sa.String(length=50), nullable=False),
    sa.Column('gas', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gwp_set_name'], ['gwp_set.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gwp_set_name', 'gas', name='uq_gwp_value_set_gas')
    )
    op.create_index(op.f('ix_gwp_value_gwp_set_name'), 'gwp_value', ['gwp_set_name'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('consolidation_approach', sa.String(length=50), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=True),
    sa.Column('gwp_set', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('track', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_organisation_id'), 'inventory', ['organisation_id'], unique=False)
    op.create_table('activity_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventory_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('ghg_category', sa.String(length=20), nullable=False),
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('fuel_key', sa.String(length=100), nullable=True),
    sa.Column('biogenic_fraction', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('biogenic_basis', sa.String(length=50), nullable=True),
    sa.Column('memo_bucket', sa.String(length=50), nullable=True),
    sa.Column('scope2_view', sa.String(length=20), nullable=True),
    sa.Column('data_quality_tier', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('currency_year', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('evidence_file_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_key'], ['activity_catalogue.activity_key'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_record_activity_key'), 'activity_record', ['activity_key'], unique=False)
    op.create_index(op.f('ix_activity_record_facility_id'), 'activity_record', ['facility_id'], unique=False)
    op.create_index(op.f('ix_activity_record_inventory_id'), 'activity_record', ['inventory_id'], unique=False)
    op.create_table('calculation_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventory_id', sa.String(length=36), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('gwp_set_name', sa.String(length=50), nullable=False),
    sa.Column('factor_set_pins', sa.JSON(), nullable=False),
    sa.Column('scope2_headline_view', sa.String(length=20), nullable=False),
    sa.Column('totals_scope1', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_scope2_location', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_scope2_market', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_scope2_headline', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_scope3', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_grand_total', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('totals_scope3_by_category', sa.JSON(), nullable=False),
    sa.Column('totals_memo', sa.JSON(), nullable=False),
    sa.Column('excluded_records', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_run_inventory_id'), 'calculation_run', ['inventory_id'], unique=False)
    op.create_table('line_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('activity_key', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('ghg_category', sa.String(length=20), nullable=False),
    sa.Column('normalised_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('normalised_unit', sa.String(length=50), nullable=True),
    sa.Column('factor_version_id', sa.String(length=100), nullable=True),
    sa.Column('factor_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('factor_source', sa.String(length=255), nullable=True),
    sa.Column('factor_reference_year', sa.Integer(), nullable=True),
    sa.Column('gas_breakdown', sa.JSON(), nullable=False),
    sa.Column('gwp_applied', sa.JSON(), nullable=False),
    sa.Column('emissions_kgco2e', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('biogenic_co2_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('memo_bucket', sa.String(length=50), nullable=True),
    sa.Column('scope2_view', sa.String(length=20), nullable=True),
    sa.Column('resolution_flags', sa.JSON(), nullable=False),
    sa.Column('data_quality_tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_result_record_id'), 'line_result', ['record_id'], unique=False)
    op.create_index(op.f('ix_line_result_run_id'), 'line_result', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_result_run_id'), table_name='line_result')
    op.drop_index(op.f('ix_line_result_record_id'), table_name='line_result')
    op.drop_table('line_result')
    op.drop_index(op.f('ix_calculation_run_inventory_id'), table_name='calculation_run')
    op.drop_table('calculation_run')
    op.drop_index(op.f('ix_activity_record_inventory_id'), table_name='activity_record')
    op.drop_index(op.f('ix_activity_record_facility_id'), table_name='activity_record')
    op.drop_index(op.f('ix_activity_record_activity_key'), table_name='activity_record')
    op.drop_table('activity_record')
    op.drop_index(op.f('ix_inventory_organisation_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_gwp_value_gwp_set_name'), table_name='gwp_value')
    op.drop_table('gwp_value')
    op.drop_index(op.f('ix_facility_organisation_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_emission_factor_region'), table_name='emission_factor')
    op.drop_index(op.f('ix_emission_factor_reference_year'), table_name='emission_factor')
    op.drop_index(op.f('ix_emission_factor_gas'), table_name='emission_factor')
    op.drop_index(op.f('ix_emission_factor_activity_key'), table_name='emission_factor')
    op.drop_table('emission_factor')
    op.drop_table('organisation')
    op.drop_table('gwp_set')
    op.drop_index(op.f('ix_fuel_property_fuel_key'), table_name='fuel_property')
    op.drop_table('fuel_property')
    op.drop_table('activity_catalogue')
    # ### end Alembic commands ###
